CREATE TABLE IF NOT EXISTS dds.dm_timestamps (
    id SERIAL PRIMARY KEY,
    ts TIMESTAMP NOT NULL,
    year SMALLINT NOT NULL CHECK (year BETWEEN 2022 AND 2499),
    month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    day SMALLINT NOT NULL CHECK (day BETWEEN 1 AND 31),
    time TIME NOT NULL,
    date DATE NOT NULL
);
